// properties-data.js - Пълни данни за всички имоти
const properties = [
    {
        id: 1,
        type: 'apartment',
        title: 'Тристаен апартамент в центъра',
        assignedBroker: "aleksandar",
        price: '€ 425,000',
        location: 'София, Център, бул. Витоша',
        area: '110 кв.м',
        floor: 'Етаж 4/8',
        rooms: '3 стаи',
        bathrooms: '2 бани',
        description: 'Луксозен тристаен апартамент с панорамна гледка към Витоша. Напълно реновиран с високи тавани и качествени материали.',
        badge: 'Луксозен',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6977, 23.3219],
        year: '2015',
        heating: 'Централно парно',
        parking: 'Подземен гараж',
        exposure: 'Юг',
        condition: 'Отлично',
        furniture: 'Напълно обзаведен',
        elevator: 'Да',
        balcony: 'Тераса 20 кв.м',
        price_per_sqm: '€ 3,864/кв.м'
    },
    {
        id: 2,
        type: 'apartment',
        title: 'Под наем: Офис пространство',
        assignedBroker: "maria",
        price: '€ 750/месец',
        location: 'София, Център, бул. Дондуков',
        area: '95 кв.м',
        floor: 'Етаж 5/8',
        rooms: '3 стаи',
        bathrooms: '2 бани',
        description: 'Просторен тристаен апартамент в престижна сграда с лифт и паркинг. Идеален за семейство или офис с красива гледка към града.',
        badge: 'Под наем',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6964, 23.3264],
        year: '2017',
        heating: 'Централно парно',
        parking: 'Подземен гараж',
        exposure: 'Югозапад',
        condition: 'Отлично',
        furniture: 'Напълно обзаведен',
        elevator: 'Да',
        balcony: 'Тераса 15 кв.м',
        price_per_sqm: '€ 7.89/кв.м'
    },
    {
        id: 3,
        type: 'apartment',
        title: 'Двустаен в нова сграда',
        assignedBroker: "elena",
        price: '€ 207,000',
        location: 'София, Красно село',
        area: '74 кв.м',
        floor: 'Етаж 3/6',
        rooms: '2 стаи',
        bathrooms: '1 баня',
        description: 'Нов двустаен апартамент в качествена сграда с паркинг и зелени площи. Отлична инвестиция в развиващ се район.',
        badge: 'Ново',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1486304873000-235643847519?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6506, 23.2819],
        year: '2023',
        heating: 'Подово отопление',
        parking: 'Паркомясто',
        exposure: 'Юг',
        condition: 'Ново строителство',
        furniture: 'Необзаведен',
        elevator: 'Да',
        balcony: 'Балкон 8 кв.м',
        price_per_sqm: '€ 2,797/кв.м'
    },
    {
        id: 4,
        type: 'land',
        title: 'Парцел за строителство',
        assignedBroker: "aleksandar",
        price: '€ 89,899',
        location: 'гр. Костинброд, кв. Маслово',
        area: '2570 кв.м',
        floor: 'Регулиран',
        rooms: 'За строеж',
        bathrooms: 'Не е приложимо',
        description: 'Голям регулиран парцел с отлична локация за жилищно строителство. Всички комуникации наблизо, асфалтов път.',
        badge: 'Регулиран',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'
        ],
        coordinates: [42.8167, 23.2167],
        year: 'Н/А',
        parking: 'Свободно паркиране',
        exposure: 'Югозапад',
        condition: 'Отлично',
        price_per_sqm: '€ 35/кв.м',
        // НОВИ СВОЙСТВА ЗА ПАРЦЕЛИ:
        parcelType: 'УПИ',
        electricity: 'Да',
        water: 'Да', 
        sewerage: 'Не',
        regulation: 'Да',
        idealProject: 'Не',
        designVisa: 'Не'
    },
    {
        id: 5,
        type: 'house',
        title: 'Семейна къща с двор',
        assignedBroker: "maria",
        price: '€ 320,000',
        location: 'София, Симеоново',
        area: '180 кв.м',
        floor: '2 етажа',
        rooms: '4 стаи',
        bathrooms: '2 бани',
        description: 'Прекрасна двуетажна къща с голям двор и гараж. Тиха локация с добра транспортна свързаност към центъра.',
        badge: 'Семейна',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6167, 23.2583],
        year: '2010',
        heating: 'Газово отопление',
        parking: 'Гараж',
        exposure: 'Югозапад',
        condition: 'Много добро',
        furniture: 'Частично обзавена',
        elevator: 'Не',
        balcony: 'Двор 400 кв.м',
        price_per_sqm: '€ 1,778/кв.м'
    },
    {
        id: 6,
        type: 'apartment',
        title: 'Студио в Студентски град',
        assignedBroker: "elena",
        price: '€ 89,000',
        location: 'София, Студентски град',
        area: '35 кв.м',
        floor: 'Етаж 2/5',
        rooms: '1 стая',
        bathrooms: '1 баня',
        description: 'Компактно студио идеално за студенти или млади специалисти. Близо до университети и метростанция.',
        badge: 'Студио',
        featured: false,
        images: [
            'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6556, 23.3397],
        year: '1985',
        heating: 'ТЕЦ',
        parking: 'Улично паркиране',
        exposure: 'Изток',
        condition: 'Добро',
        furniture: 'Обзаведен',
        elevator: 'Не',
        balcony: 'Балкон 3 кв.м',
        price_per_sqm: '€ 2,543/кв.м'
    },
    {
        id: 7,
        type: 'commercial',
        title: 'Магазин на партер',
        assignedBroker: "elena",
        price: '€ 150,000',
        location: 'София, Лозенец',
        area: '65 кв.м',
        floor: 'Партер',
        rooms: 'Търговско помещение',
        bathrooms: '1 баня',
        description: 'Търговско помещение на оживена улица в престижен район. Подходящо за различни видове бизнес.',
        badge: 'Търговски',
        featured: false,
        images: [
            'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6722, 23.3308],
        year: '2005',
        heating: 'Климатик',
        parking: 'Улично паркиране',
        exposure: 'Запад',
        condition: 'Отлично',
        furniture: 'Необзаведен',
        elevator: 'Не',
        balcony: 'Няма',
        price_per_sqm: '€ 2,308/кв.м'
    },
    {
        id: 8,
        type: 'apartment',
        title: 'Мансарда в Борово',
        assignedBroker: "elena",
        price: '€ 165,000',
        location: 'София, Борово',
        area: '85 кв.м',
        floor: 'Етаж 6/6',
        rooms: '3 стаи',
        bathrooms: '1 баня',
        description: 'Просторна мансарда с уникална архитектура и красива гледка. Тих район с добра инфраструктура.',
        badge: 'Мансарда',
        featured: false,
        images: [
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6167, 23.4],
        year: '1995',
        heating: 'Локално парно',
        parking: 'Двор за паркиране',
        exposure: 'Север',
        condition: 'Добро',
        furniture: 'Частично обзавена',
        elevator: 'Не',
        balcony: 'Мансардни прозорци',
        price_per_sqm: '€ 1,941/кв.м'
    },
    {
        id: 9,
        type: 'house',
        title: 'Еднофамилна къща',
        assignedBroker: "elena",
        price: '€ 280,000',
        location: 'гр. Перник',
        area: '120 кв.м',
        floor: '1 етаж',
        rooms: '3 стаи',
        bathrooms: '1 баня',
        description: 'Удобна едноетажна къща с голям двор в спокоен район. Подходяща за пенсионери или семейства с деца.',
        badge: 'Едноетажна',
        featured: false,
        images: [
            'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6, 23.0333],
        year: '2000',
        heating: 'Климатик',
        parking: 'Двор',
        exposure: 'Юг',
        condition: 'Много добро',
        furniture: 'Обзаведена',
        elevator: 'Не',
        balcony: 'Веранда',
        price_per_sqm: '€ 2,333/кв.м'
    },
    {
        id: 10,
        type: 'house',
        title: 'Вила с басейн',
        assignedBroker: "elena",
        price: '€ 850,000',
        location: 'София, Драгалевци',
        area: '280 кв.м',
        floor: '2 етажа + сутерен',
        rooms: '5 стаи',
        bathrooms: '3 бани',
        description: 'Луксозна вила с басейн и прекрасна гледка към планината. Голям двор с ландшафтна градина и барбекю зона.',
        badge: 'Вила',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6167, 23.2583],
        year: '2018',
        heating: 'Подово отопление + климатици',
        parking: 'Гараж за 3 коли',
        exposure: 'Югозапад',
        condition: 'Ново',
        furniture: 'Луксозно обзавена',
        elevator: 'Да',
        balcony: 'Двор с басейн 1200 кв.м',
        price_per_sqm: '€ 3,179/кв.м'
    },
    {
        id: 11,
        type: 'apartment',
        title: 'Едностаен в Младост',
        assignedBroker: "elena",
        price: '€ 145,000',
        location: 'София, Младост 1',
        area: '45 кв.м',
        floor: 'Етаж 3/8',
        rooms: '1 стая',
        bathrooms: '1 баня',
        description: 'Компактен едностаен апартамент с модерен дизайн. Отлично за млади хора или като инвестиция за отдаване под наем.',
        badge: 'Младежки',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=800&h=600&fit=crop'
        ],
        coordinates: [42.7031, 23.2369],
        year: '1980',
        heating: 'ТЕЦ',
        parking: 'Улично паркиране',
        exposure: 'Изток',
        condition: 'Реновиран',
        furniture: 'Обзаведен',
        elevator: 'Да',
        balcony: 'Френски балкон',
        price_per_sqm: '€ 3,222/кв.м'
    },
    {
        id: 12,
        type: 'apartment',
        title: 'Тристаен с тераса',
        assignedBroker: "elena",
        price: '€ 385,000',
        location: 'София, Витоша',
        area: '115 кв.м',
        floor: 'Етаж 7/8',
        rooms: '3 стаи',
        bathrooms: '2 бани',
        description: 'Просторен апартамент с голяма тераса и гледка към Витоша. Паркомясто включено в цената.',
        badge: 'Тераса',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6722, 23.3308],
        year: '2012',
        heating: 'Централно парно',
        parking: 'Паркомясто в цената',
        exposure: 'Югозапад',
        condition: 'Отлично',
        furniture: 'Частично обзаведен',
        elevator: 'Да',
        balcony: 'Тераса 25 кв.м',
        price_per_sqm: '€ 3,348/кв.м'
    },
    {
        id: 13,
        type: 'house',
        title: 'Двуетажна къща',
        assignedBroker: "elena",
        price: '€ 275,000',
        location: 'гр. Ботевград',
        area: '150 кв.м',
        floor: '2 етажа',
        rooms: '3 спални',
        bathrooms: '2 бани',
        description: 'Нова двуетажна къща с голям двор. Идеална за семейство търсещо спокойствие далеч от градския шум.',
        badge: 'Извънградска',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop'
        ],
        coordinates: [42.9167, 23.7833],
        year: '2020',
        heating: 'Газово отопление',
        parking: 'Двор за паркиране',
        exposure: 'Юг',
        condition: 'Ново строителство',
        furniture: 'Необзавена',
        elevator: 'Не',
        balcony: 'Двор 800 кв.м',
        price_per_sqm: '€ 1,833/кв.м'
    },
    {
        id: 14,
        type: 'apartment',
        title: 'Мезонет в центъра',
        assignedBroker: "elena",
        price: '€ 650,000',
        location: 'София, Център, ул. Граф Игнатиев',
        area: '165 кв.м',
        floor: 'Етаж 5-6/6',
        rooms: '4 стаи',
        bathrooms: '3 бани',
        description: 'Уникален мезонет на два етажа с висококачествени материали и дизайнерски интериор. Рядка възможност в центъра.',
        badge: 'Мезонет',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6964, 23.3219],
        year: '2008',
        heating: 'Централно парно',
        parking: 'Подземен гараж',
        exposure: 'Юг',
        condition: 'Луксозно',
        furniture: 'Дизайнерски интериор',
        elevator: 'Да',
        balcony: 'Тераса на покрива',
        price_per_sqm: '€ 3,939/кв.м'
    },
    {
        id: 15,
        type: 'commercial',
        title: 'Офис сграда',
        assignedBroker: "elena",
        price: '€ 1,850,000',
        location: 'София, Бизнес Парк',
        area: '850 кв.м',
        floor: '4 етажа',
        rooms: 'Офисни помещения',
        bathrooms: 'Множество',
        description: 'Модерна офис сграда с отлична локация. Напълно оборудвана и готова за ползване от голяма компания.',
        badge: 'Инвестиция',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6508, 23.3833],
        year: '2016',
        heating: 'Централна климатизация',
        parking: 'Подземен паркинг',
        exposure: 'Всички страни',
        condition: 'Ново',
        furniture: 'Офис обзавеждане',
        elevator: 'Множество асансьора',
        balcony: 'Офисни тераси',
        price_per_sqm: '€ 2,176/кв.м'
    },
    {
        id: 16,
        type: 'land',
        title: 'Парцел в планински район',
        assignedBroker: "elena",
        price: '€ 45,000',
        location: 'Витоша, с. Железница',
        area: '1200 кв.м',
        floor: 'Неурбанизиран',
        rooms: 'За почивна къща',
        bathrooms: 'Не е приложимо',
        description: 'Парцел с красива гледка към Витоша, подходящ за почивна къща. Тих и спокоен район сред природата.',
        badge: 'Планински',
        featured: false,
        images: [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop'
        ],
        coordinates: [42.5833, 23.1833],
        year: 'Н/А',
        heating: 'Н/А',
        parking: 'Неограничен',
        exposure: 'Панорамна гледка',
        condition: 'Естествен терен',
        furniture: 'Н/А',
        elevator: 'Н/А',
        balcony: 'Цял парцел',
        price_per_sqm: '€ 37.5/кв.м',
        // НОВИ СВОЙСТВА ЗА ПАРЦЕЛИ:
        parcelType: 'ПИ',
        electricity: 'Не',
        water: 'Не', 
        sewerage: 'Не',
        regulation: 'Не',
        idealProject: 'Не',
        designVisa: 'Не'
    },
    {
        id: 17,
        type: 'house',
        title: 'Първи етаж от двуетажна къща',
        assignedBroker: "elena",
        price: '€ 180,000',
        location: 'София, Горна баня',
        area: '90 кв.м',
        floor: '2 етажа',
        forSaleFloor: '1',
        forSaleFloorTotal: '2',
        forSaleFloorNote: '',
        rooms: '3 стаи',
        bathrooms: '1 баня',
        description: 'Продава се само първият етаж от двуетажна къща с отделен вход и двор. Отлична възможност за самостоятелно жилище.',
        badge: 'Само етаж',
        featured: false,
        images: [
            'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1460518451285-97b6aa326961?w=800&h=600&fit=crop'
        ],
        coordinates: [42.6700, 23.2700],
        year: '2000',
        heating: 'Климатик',
        parking: 'Двор',
        exposure: 'Юг',
        condition: 'Много добро',
        furniture: 'Обзаведен',
        elevator: 'Не',
        balcony: 'Двор 200 кв.м',
        price_per_sqm: '€ 2,000/кв.м'
    },
    {
        id: 18,
        type: 'land',
        title: 'УПИ в жилищна зона',
        assignedBroker: "elena",
        price: '€ 125,000',
        location: 'София, кв. Банишора',
        area: '850 кв.м',
        floor: 'Регулиран УПИ',
        rooms: 'За жилищно строителство',
        bathrooms: 'Не е приложимо',
        description: 'Отличен регулиран парцел в развиващ се район. Всички комуникации налични, готов за строителство на жилищна сграда.',
        badge: 'УПИ',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'
        ],
        coordinates: [42.7167, 23.2667],
        year: 'Н/А',
        parking: 'Свободно паркиране',
        exposure: 'Юг',
        condition: 'Отлично',
        price_per_sqm: '€ 147/кв.м',
        // НОВИ СВОЙСТВА ЗА ПАРЦЕЛИ:
        parcelType: 'УПИ',
        electricity: 'Да',
        water: 'Да', 
        sewerage: 'Да',
        regulation: 'Да',
        idealProject: 'Да',
        designVisa: 'Да'
    },
    {
        id: 19,
        type: 'land',
        title: 'Земеделска земя',
        assignedBroker: "elena",
        price: '€ 25,000',
        location: 'с. Долни Богров',
        area: '5000 кв.м',
        floor: 'Земеделска земя',
        rooms: 'За земеделие',
        bathrooms: 'Не е приложимо',
        description: 'Голям парцел земеделска земя с възможност за промяна на предназначението. Добър достъп с черен път.',
        badge: 'Земеделска',
        featured: false,
        images: [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop'
        ],
        coordinates: [42.7500, 23.4167],
        year: 'Н/А',
        parking: 'Свободно паркиране',
        exposure: 'Всички страни',
        condition: 'Земеделска земя',
        price_per_sqm: '€ 5/кв.м',
        // НОВИ СВОЙСТВА ЗА ПАРЦЕЛИ:
        parcelType: 'ПИ',
        electricity: 'Не',
        water: 'Не', 
        sewerage: 'Не',
        regulation: 'Не',
        idealProject: 'Не',
        designVisa: 'Не'
    },
    {
        id: 20,
        type: 'land',
        title: 'Парцел за вила',
        assignedBroker: "elena",
        price: '€ 180,000',
        location: 'Панчарево',
        area: '1800 кв.м',
        floor: 'Регулиран за вили',
        rooms: 'За вилно строителство',
        bathrooms: 'Не е приложимо',
        description: 'Прекрасен парцел в престижен район за вили. Близо до язовира с отлична гледка и чист въздух.',
        badge: 'Вилна зона',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'
        ],
        coordinates: [42.5833, 23.4167],
        year: 'Н/А',
        parking: 'Свободно паркиране',
        exposure: 'Югоизток',
        condition: 'Отлично',
        price_per_sqm: '€ 100/кв.м',
        // НОВИ СВОЙСТВА ЗА ПАРЦЕЛИ:
        parcelType: 'УПИ',
        electricity: 'Да',
        water: 'Да', 
        sewerage: 'Не',
        regulation: 'Да',
        idealProject: 'Не',
        designVisa: 'Не'
    }
];

// For backward compatibility, also create mapProperties from the same data
const mapProperties = properties.map(property => ({
    id: property.id,
    type: property.type,
    title: property.title,
    price: property.price,
    location: property.location,
    area: property.area,
    rooms: property.rooms,
    coordinates: property.coordinates,
    description: property.description
}));